CREATE TABLE dbo.cases_raw_2024 (
  system_generated_id varchar(50) NOT NULL,
  case_id varchar(50) NOT NULL,
  open_date varchar(50) NOT NULL,
  sla_target_date varchar(50) NULL,
  closed_date varchar(50) NULL,
  on_time varchar(20) NOT NULL,
  case_status varchar(20) NOT NULL,
  closure_reason varchar(4000) NULL,
  case_topic varchar(255) NULL,
  assigned_department varchar(500) NOT NULL,
  assigned_team varchar(500) NOT NULL,
  service_name varchar(500) NOT NULL,
  queue varchar(500) NOT NULL,
  assignment_department varchar(50) NOT NULL,
  submitted_photo varchar(2000) NULL,
  closed_photo varchar(2000) NULL,
  location varchar(1000) NULL,
  fire_district varchar(255) NULL,
  public_works_district varchar(255) NULL,
  city_council_district varchar(50) NULL,
  police_district varchar(255) NULL,
  neighborhood varchar(150) NULL,
  neighborhood_services_district varchar(50) NULL,
  ward varchar(20) NULL,
  precinct varchar(50) NULL,
  location_street_name varchar(500) NULL,
  location_zipcode varchar(10) NULL,
  latitude varchar(50) NULL,
  longitude varchar(50) NULL,
  source varchar(100) NOT NULL
);
GO